print("List Function         :names.sort()")
names=['Mohan','Jegan','Karthi','Bala','Selva']
print("My  List names        :",names)
print("List Methods Value    :",names.sort())
print("List Methods Value    :",names)
print("========================================")
print("List Function         :names.sort(reverse=True)")
names=['Mohan','Jegan','Karthi','Bala','Selva']
print("My  List names        :",names)
print("List Methods Value    :",names.sort(reverse=True))
print("List Methods Value    :",names)
print("========================================")
print("List Function         :names.sort()")
names=[4,2,7,4,2,3,9,7]
print("My  List names        :",names)
print("List Methods Value    :",names.sort())
print("List Methods Value    :",names)
print("========================================")
print("List Function         :names.sort(reverse=True)")
names=[4,2,7,4,2,3,9,7]
print("My  List names        :",names)
print("List Methods Value    :",names.sort(reverse=True))
print("List Methods Value    :",names)
print("========================================")
print("List Function         :names.sort(key=len)")
names=['Mohan','Jegan','Karthi','Bala','Selva']
print("My  List names        :",names)
print("List Methods Value    :",names.sort(key=len))
print("List Methods Value    :",names)
print("========================================")
