print("List Function         :sorted(names)")
names=['Mohan','Jegan','Karthi','Bala','Selva']
print("My  List names        :",names)
print("List Methods Value    :",sorted(names))
# print("List Methods Value    :",names)
print("========================================")
print("List Function         :sorted(names,(reverse=True)")
names=['Mohan','Jegan','Karthi','Bala','Selva']
print("My  List names        :",names)
print("List Methods Value    :",sorted(names,reverse=True))
# print("List Methods Value    :",names)
print("========================================")
print("List Function         :sorted(names,()")
names=[4,2,7,4,2,3,9,7]
print("My  List names        :",names)
print("List Methods Value    :",sorted(names))
# print("List Methods Value    :",names)
print("========================================")
print("List Function         :sorted(names,(reverse=True)")
names=[4,2,7,4,2,3,9,7]
print("My  List names        :",names)
print("List Methods Value    :",sorted(names,reverse=True))
# print("List Methods Value    :",names)
print("========================================")
print("List Function         :sorted(names,(key=len)")
names=['Mohan','Jegan','Karthi','Bala','Selva']
print("My  List names        :",names)
print("List Methods Value    :",sorted(names,key=len))
# print("List Methods Value    :",names)
print("========================================")
