console.log("String Function      : s.slice(3,6)")
console.log("slice(startindex,endindex(optinal))")
let s='Web Development'
console.log("My String S          :",s)
console.log("Stirng Methods Value :",s.slice(3,6))
console.log("=====================================")
console.log("String Function      : s.slice(3,6)")
// console.log("slice(startindex,endindex(optinal))")
s='Web Development'
console.log("My String S          :",s)
console.log("Stirng Methods Value :",s.slice(3))
console.log("=====================================")
console.log("String Function      : s.slice(8,1)")
// console.log("slice(startindex,endindex(optinal))")
console.log('when you were starting index higher ,ending index low , no automatically correct(8,1)(1,8) ')
s='Web Development'
console.log("My String S          :",s)
console.log("Stirng Methods Value :",s.slice(8,1))
console.log("=====================================")
console.log("String Function      : s.slice(30,40)")
console.log("slice(startindex,endindex(optinal))")
 s='Web Development'
console.log("My String S          :",s)
console.log("Stirng Methods Value :",s.slice(30,40))
console.log("=====================================")
console.log("String Function      : s.slice(-3)")
// console.log("slice(startindex,endindex(optinal))")
s='Web Development'
console.log("My String S          :",s)
console.log("Stirng Methods Value :",s.slice(-3))
console.log("=====================================")