console.log("String Function      : s.substring(3,6)")
console.log("substring(startindex,endindex(optinal))")
let s='Web Development'
console.log("My String S          :",s)
console.log("Stirng Methods Value :",s.substring(3,6))
console.log("=====================================")
console.log("String Function      : s.substring(3,6)")
// console.log("substring(startindex,endindex(optinal))")
s='Web Development'
console.log("My String S          :",s)
console.log("Stirng Methods Value :",s.substring(3))
console.log("=====================================")
console.log("String Function      : s.substring(8,1)")
// console.log("substring(startindex,endindex(optinal))")
 console.log('when you were starting index higher ,ending index low ,  automatically correct(8,1)(1,8) ')
s='Web Development'
console.log("My String S          :",s)
console.log("Stirng Methods Value :",s.substring(8,1))
console.log("=====================================")
console.log("String Function      : s.substring(30,40)")
console.log("substring(startindex,endindex(optinal))")
 s='Web Development'
console.log("My String S          :",s)
console.log("Stirng Methods Value :",s.substring(30,40))
console.log("=====================================")
