print("Tuble Function         :names.count('Mohan')")
names=('Mohan','Jegan','Karthi','Bala','Selva')
print("My  Tuble names        :",names)
print("Tuble Methods Value    :",names.count('Mohan'))
print("===============================================")
print("Tuble Function         :names.count('Mohan')")
names=('Mohan','Jegan','Karthi','Bala','Selva',"Mohan")
print("My  Tuble names        :",names)
print("Tuble Methods Value    :",names.count('Mohan'))
print("===============================================")
