print("Tuble Function         :names.index('Mohan')")
names=('Mohan','Jegan','Karthi','Bala','Selva')
print("My  Tuble names        :",names)
print("Tuble Methods Value    :",names.index('Mohan'))
print("===============================================")
print("Tuble Function         :names.index('Jegan')")
names=('Mohan','Jegan','Karthi','Bala','Selva')
print("My  Tuble names        :",names)
print("Tuble Methods Value    :",names.index('Jegan'))
print("===============================================")