# print("Tuble Function         :names.()")
names=('Mohan','Jegan','Karthi','Bala','Selva')
# print("My  Tuble names        :",names)
# print("Tuble Methods Value    :",names.())
# print("Tuble Methods Value    :",names.())
print('Type :',type(names),"Value :",names)
print('List is sequence type')
print('access index ')
print('immutable')