console.log('Map Object :')
let user=new Map ()
console.log("Type :",typeof user,",Value :",user)
console.log('Map store value is kay and value')
console.log('Map Object Methods :')
console.log("List Function      : user.set('fullname','Mohan')")
console.log("My  set names     :",user)
console.log("List Methods Value :",user.set('fullname','Mohan'))
console.log("=====================================")
console.log("List Function      : user.get('fullname')")
console.log("My  set names     :",user)
console.log("List Methods Value :",user.get('fullname'))
console.log("=====================================")
console.log("List Function      : user.size")
console.log("My  set names     :",user)
console.log("List Methods Value :",user.size)
console.log("=====================================")
console.log("List Function      : user.has('fullname')")
console.log("My  set names     :",user)
console.log("List Methods Value :",user.has('fullname'))
console.log("=====================================")
console.log("List Function      : user.keys()")
console.log("My  set names     :",user)
console.log("List Methods Value :",user.keys().next().value)
console.log("=====================================")
console.log("List Function      : user.values().next().value")
console.log("My  set names     :",user)
console.log("List Methods Value :",user.values().next().value)
console.log("=====================================")
