console.log('Set Object :')
let names=new Set()
console.log("Type :",typeof names,",Value :",names)
console.log('set is automatically delete dublicate value')
console.log('Set Object Methods :')
console.log("List Function      : set.add('Mohan')")
console.log("My  set names     :",names)
console.log("List Methods Value :",names.add("Mohan"))
console.log("=====================================")
console.log("List Function      : set.has('Mohan')")
console.log("My  set names     :",names)
console.log("List Methods Value :",names.has('Mohan'))
console.log("=====================================")
console.log("List Function      : set.has('jegan')")
console.log("My  set names     :",names)
console.log("List Methods Value :",names.has('jegan'))
console.log("=====================================")
console.log("List Function      : set.delete('Mohan')")
console.log("My  set names     :",names)
console.log("List Methods Value :",names.delete('Mohan'))
console.log("=====================================")
console.log("List Function      : set.delete('jegan')")
console.log("My  set names     :",names)
console.log("List Methods Value :",names.delete('jegan'))
console.log("=====================================")