names=(["Mohan",34,'salem'],["Jegan",21,'Erode'],["Karthi",23,'sangiri'])
# print("Function sort :")
# print("Index 0 based :")
# print("My List Names is :",names)
# names.sort(key=lambda a:a[0])
# print("Sort Names       :",names)
# print("Index 1 based :")
# print("My List Names is :",names)
# names.sort(key=lambda a:a[1])
# print("Sort Names       :",names)
# print("Index 2 based :")
# print("My List Names is :",names)
# names.sort(key=lambda a:a[2])
print("Sort Names       :",names)
print("=========================================================================")
print("Function sorted :")
print("Index 0 based :")
print("My List Names is :",names)
print("Sort Names :",tuple(sorted(names,key= lambda a:a[0])))
print("Index 1 based :")
print("My List Names is :",names)
print("Sort Names :",tuple(sorted(names,key= lambda a:a[1])))
print("Index 2 based :")
print("My List Names is :",names)
print("Sort Names :",tuple(sorted(names,key= lambda a:a[2])))
