console.log('Console function : log ')
console.log('log ')
console.log('Console function : Error ')
console.error("error ")
console.log("Console function :  Table ")
console.table({name:"Mohan",age:25})
console.log("Console function :  warning ")
console.warn("warn ")
console.log('Console function : Clear ')
console.clear()
console.log("Console function : time  ")
console.time('Timer')
console.log("simple console")
console.log('console time and timeEnd parameters is Timer')
console.timeEnd('Timer')