console.log("Math Functions")
// console.log('Math Function(Math.) :',Math)
console.log('Math Function(Math.PI)            :',Math.PI)
console.log('Math Function(Math.E)             :',Math.E)
console.log('Math Function(Math.LN2)           :',Math.LN2)
console.log('Math Function(Math.round(4.6))    :',Math.round(4.6))
console.log('Math Function(Math.round(4.5))    :',Math.round(4.5))
console.log('Math Function(Math.round(4.4))    :',Math.round(4.4))
console.log('Math Function(Math.abs(-3))       :',Math.abs(-3))
console.log('Math Function(Math.abs(3))        :',Math.abs(3))
console.log('Math Function(Math.floor(3.4567)) :',Math.floor(3.4567))
console.log('Math Function(Math.ceil(3.6))     :',Math.ceil(3.6))
console.log('Math Function(Math.ceil(3.5))     :',Math.ceil(3.5))
console.log('Math Function(Math.ceil(3.4))     :',Math.ceil(3.4))
console.log('Math Function(Math.sqrt(4))       :',Math.sqrt(4))
console.log('Math Function(Math.trunc(3.68))   :',Math.trunc(3.68))
console.log('Math Function(Math.pow(3,2))      :',Math.pow(3,2))
console.log('Math Function(Math.pow(bash,root)')
console.log('Math Function(Math.min(2,3,4))    :',Math.min(2,3,4))
console.log('Math Function(Math.max(2,3,4))    :',Math.max(2,3,4))
console.log('Math Function(Math.randam())        :',Math.random())
console.log('Math Function(Math.sign(+7))      :',Math.sign(+7))
console.log('Math Function(Math.sign(0))       :',Math.sign(0))
console.log('Math Function(Math.sign(-8))      :',Math.sign(-8))