import math
print("math Functions")
#  print('math Function(math.) :',math)
print('math Function(math.pi)            :',math.pi)
print('math Function(math.e)             :',math.e)
# print('math Function(math.LN2)           :',math.)
# print('math Function(math.round(4.6))    :',math.round(4.6))
# print('math Function(math.round(4.5))    :',math.round(4.5))
# print('math Function(math.round(4.4))    :',math.round(4.4))
print('math Function(math.abs(-3))       :',math.fabs(-3))
print('math Function(math.abs(3))        :',math.fabs(3))
print('math Function(math.floor(3.4567)) :',math.floor(3.4567))
print('math Function(math.ceil(3.6))     :',math.ceil(3.6))
print('math Function(math.ceil(3.5))     :',math.ceil(3.5))
print('math Function(math.ceil(3.4))     :',math.ceil(3.4))
print('math Function(math.sqrt(4))       :',math.sqrt(4))
print('math Function(math.trunc(3.68))   :',math.trunc(3.68))
print('math Function(math.pow(3,2))      :',math.pow(3,2))
print('math Function(math.pow(bash,root)')
print('math Function(math.factorial(5)   :',math.factorial(5))

