print('python is an interpretd ,object-oriented,high level languages')
print('first developed by 1980s by guide van Rossum')
print('python open sourse ')
print('guide van rossum named after the BBC comedy Tv series Monty python flying cicus')
print('Advantages :')
print('python is easy to learn and use')
print('large number of libraries avalable that can be used in Your projects')
print('Portable across operating systems')
print('Organizations using python :')
print('Google,microsoft,facebook,mozilla,youtube, ')
print('Python Based Jobs :')
print('Data Analysis,AI,automation,web app,desktop app,hacking')