number=24
string=None
boolean=True
floats=24.6
print("Type :",type( number),"Value :",number)
print("Type :",type( string),"Value :",string)
print("Type :",type( boolean),"Value :",boolean)
print("Type :",type( floats),"Value :",floats)
print("After Type Casting (Str) :")
print("Type :",type(str (number)),"Value :",str (number))
print("Type :",type(str (string)),"Value :",str (string))
print("Type :",type(str (boolean)),"Value :",str (boolean))
print("Type :",type(str (floats)),"Value :",str (floats))
print("After Type Casting (int) :")
print("String is only numbers string change ")
print("Type :",type(int (number)),"Value :",int (number))
# print("Type :",type(str (string)),"Value :",str (string))
print("Type :",type(int (boolean)),"Value :",int (boolean))
print("Type :",type(int (floats)),"Value :",int (floats))
print("After Type Casting (bool) :")
print("bool is your change value empty return False")
print("Type :",type(bool (number)),"Value :",bool (number))
print("Type :",type(bool (string)),"Value :",bool (string))
print("Type :",type(bool (boolean)),"Value :",bool (boolean))
print("Type :",type(bool (floats)),"Value :",bool (floats))
print("After Type Casting (Float) :")
print("bool is your change value empty return False")
print("Type :",type(float (number)),"Value :",float (number))
print("String is only Float numbers string change ")
# print("Type :",type(float (string)),"Value :",float (string))
print("Type :",type(float (boolean)),"Value :",float (boolean))
print("Type :",type(float (floats)),"Value :",float(floats))