console.log("List Function      : names.splice(2,4)")
let names=['Mohan','Jegan','Karthi','Bala','Selva']
console.log("My  List names     :",names)
console.log("List Methods apply :",names.splice(2,4))
console.log("List Methods Value :",names)
console.log(" ===============================================================")
console.log("List Function      : names.splice(2)")
names=['Mohan','Jegan','Karthi','Bala','Selva']
console.log("My  List names     :",names)
console.log("List Methods apply :",names.splice(1))
console.log("List Methods Value :",names)
console.log(" ===============================================================")
console.log("List Function      : names.splice(2,4,'Anbu')")
names=['Mohan','Jegan','Karthi','Bala','Selva']
console.log("My  List names     :",names)
console.log("List Methods apply :",names.splice(2,4,'Anbu'))
console.log("List Methods Value :",names)
console.log(" ===============================================================")
console.log("List Function      : names.splice(2,0,'Anbu')")
names=['Mohan','Jegan','Karthi','Bala','Selva']
console.log("My  List names     :",names)
console.log("List Methods Apply :",names.splice(2,0,'Anbu'))
console.log("List Methods Value :",names)
console.log(" ===============================================================")
console.log("List Function      : names.splice()")
 names=['Mohan','Jegan','Karthi','Bala','Selva']
console.log("My  List names     :",names)
console.log("List Methods Value :",names.splice())
console.log("List Methods Value :",names)
console.log(" ===============================================================")
console.log("you change values original values is change")
console.log('splice(start,length,new element)')
