msg="Welcome"
value_float=3.1234
value_int=4
salary=10000000
# print("Msg         :",msg)
# print('Value_float :',value_float)
print('Value_int   :',value_int)
print("================================")
print("Before format :string")
print("Msg           :",msg)
print("After format  :string")
print(f'*********1.{msg}*********')
print(f'*********2.{msg:20}*********')
print(f'*********3.{msg:>20}*********')
print(f'*********4.{msg:<20}*********')
print(f'*********5.{msg:^20}*********')
print("=====================================")
print("Before format :float")
print('Value_float   :',value_float)
print("After format  :float")
print(f'1.value       : {value_float:.2f}')
print(f'2.value       : {value_float:.3f}')
print("=====================================")
print("Before format :int")
print("Salary        :",salary)
print("After format  :int")
print(f'Salary       :{salary:,}')
print("======================================")
print("Before format      :int")
print("Value              :",value_int)
print("After format       :int")
print(f'Value(octal)       :{value_int:o}')
print(f'Value(binary)      :{value_int:b}')
print(f'Value(hexa)        :{value_int:x}')
print(f'Value(scientific)  :{value_int:e}')